site_name: PyTemplate
site_description: A Python archetype documentation to help developers to start developing a coding project.
repo_url: https://github.com/charlstown/py-template.git

# Configuration
# Theme
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.svg
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Sorting menu pages
nav:
    - Home: 'index.md'
    - User Guide:
      - Getting Started: 'user-guide/getting-started.md'
      - Set Up: 'user-guide/set-up.md'
      - Usage: 'user-guide/usage.md'
      - CI CD: 'user-guide/ci-cd.md'
    - Dev Guide:
      - Contribute: 'dev-guide/contribute.md'
      - Document: 'dev-guide/document.md'
    - References: 'references.md'


# Extensions
markdown_extensions:
  - pymdownx.details