# Configuration file for the project My Python Project
# Author/s: Carlos Grande
# -----------------------------------------------------
# Date: 03/01/2023
# License: MIT
# Version: 0.1.0
# Maintainer: Carlos Grande
# -----------------------------------------------------

# Configuration parameters
project_name: "my-python-project"
path_logs: data/logs/file.log

# >>> Add your configuration parameters here <<<

# ⌄⌄⌄ Example. Not actual parameters, remove before code. ⌄⌄⌄
example_string: This is an string
example_integer: 2077
example_float: 2.077
example_boolean: True
example_none: None
example_list:
 - A
 - B
 - C
example_dictionary:
 key_a: value_a
 key_b: value_b
example_set: !!set
 ? a
 ? b
 ? 1
 ? 2
example_anchor: &my_anchor data_to_duplicate
example_run_anchor: *my_anchor
# ⌃⌃⌃ Example. Not actual parameters, remove before code. ⌃⌃⌃
