# Action to run the template and test the project generated
name: On Push Run Template # Workflow name

on: push # Trigger

jobs: # Jobs to run
  deploy:
    name: run-archetype  # Name of the job
    runs-on: ubuntu-latest  # Operating system to run the job on
    steps:  # Steps to run
    - uses: actions/checkout@v2 # Action to run
    - name: Set up Python # Name of the step
      uses: actions/setup-python@v4.3.0  # Action to run
      with:
        python-version: '3.10' # Python version
    - name: Install dependencies # Step to install dependencies
      run: | # Commands to install requirements and cookiecutter
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        pip install cookiecutter
    - name: Run main.py  # Step to run the script
      run: | # Commands to create the cookiecutter template and run the project
        cd ..
        cookiecutter --no-input ./py-template
        cd my-python-project
        python src/my_python_project/main.py -l debug
